import { TheHeader } from '@/component/TheHeader'
//import './globals.css'
import { Inter } from 'next/font/google'
import { TheFooter } from '@/component/TheFooter'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <TheHeader/>
        <main className='container'>{children}</main>
        <TheFooter />
      </body>
    </html>
  )
}
